### ISSUE TITLE
Https handling

### ISSUE THREAD

**Issue by lanbus** [CERT-BDF/TheHive#111]
# EDIT THIS TITLE BEFORE POSTING. Use this template for bug reports. If you'd like to request a feature, please be as descriptive as possible and delete the template except the first section (Request Type)

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Windows
| TheHive version / git hash   | 2.10.0
| Package Type              | Binary
| Browser type & version    | If applicable

### Problem Description
Implementation of HTTPS disappeared from the wiki. the https does not take the certificate. 

### Steps to Reproduce
1. I created a truststore.jks and added the key.
2.Created the CSR, completed it with my AC. And put  back the certificate in the truststore.
3. Added the ca to the cacerts of java using keytool command : 
keytool -keystore cacerts -importcert -alias ca -file ca.crt
4. I added those lines to my application.conf file : 
https.port: 9443
play.server.https.keystore {
        path: "/opt/truststore.jks"
        type: "JKS"
        password: "MyPassword"
}
5. I still get the default self-signed certificate.

7. I was looking to read more the documentation that you had but it disappeared from the wiki ?

### Exceptionnelle information
6. When I go into the logs I can see that message :  ticketingcert thehive[1402]: io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: unknown_ca

**Comment by saadkadhi** [comment]
Hello @lanbus

Good catch. We have updated the FAQ to point to the new [Configuration guide](https://github.com/CERT-BDF/TheHive/wiki/Configuration]. You'll find the [relevant section in it](https://github.com/CERT-BDF/TheHive/wiki/Configuration#9-https).

Make sure to check out the [Digital Ocean tutorial](https://www.digitalocean.com/community/tutorials/java-keytool-essentials-working-with-java-keystores) that section points to.
 
Let us know if that works for you and if we can close the issue.

**Comment by lanbus** [comment]
Hello,
Thanks for the documentation :)
I did the process from scratch a second time. 
I have my certificate in my truststore : 
Type de fichier de clés : JKS
Fournisseur de fichier de clés : SUN

Votre fichier de clés d'accès contient 1 entrée

ticketingcert, 9 févr. 2017, PrivateKeyEntry,
Empreinte du certificat (SHA1) : F7:E1:18:11:78:C3:E8:40:34:50:D3:D7:9A:EB:3D:FA:40:3F:73:F2


The certificate of the ca is in the system. 
Le certificat existe déjà dans le fichier de clés d'accès CA système sous l'alias <ca>

but I still get the error
 p.c.s.s.DefaultSSLEngineProvider - Using generated key with self signed certificate for HTTPS. This should not be used in production.
Feb  9 10:24:00 ticketingcert thehive[6449]: [#033[31merror#033[0m] p.c.s.n.PlayRequestHandler - Exception caught in Netty
Feb  9 10:24:00 ticketingcert thehive[6449]: io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: unknown_ca

In fact, I even tried to remove all the play.server.https.keystore part and it still gives me the same message. 

All errors and information on certificate appears only when I try to load the webpage in https. So I don't really know if this part is used in the configuration file.

**Comment by JohnOmernik** [comment]
I have found the same issues.  Based on getting SSL to work with other apps, I decided I may need a truststore password as well, so in addition to the information about the key store in the application.conf, I also added

bin/thehive -Dconfig.file=/opt/thehive/etc/application.conf -Djavax.net.ssl.trustStore=/opt/thehive/certs/myTrustStore.jts -Djavax.net.ssl.trustStorePassword="mysupersekritpassword"

(This I have a trustStore and a trustStorePassword both passed in via -D) That said, even with providing the trust store, the key store, and the passwords, (which I don't like having to provide a trust store password at the command line by the way). I am still getting the same error above (which is thehive generates a self signed certificate).  It's like the information for the truststore or keystore isn't being read properly, so it generates a self signed cert... but it's providing helpful information about what isn't working... 

My stack trace:

[[37minfo[0m] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
[[37minfo[0m] p.c.s.NettyServer - Listening for HTTPS on /0:0:0:0:0:0:0:0:30943
[[33mwarn[0m] p.c.s.s.DefaultSSLEngineProvider - Using generated key with self signed certificate for HTTPS. This should not be used in production.
[[37minfo[0m] p.c.s.s.FakeKeyStore - Generating HTTPS key pair in /opt/thehive/thehive-2.10.0/conf/generated.keystore - this may take some time. If nothing happens, try moving the mouse/typing on the keyboard to generate some entropy.
[[31merror[0m] p.c.s.n.PlayRequestHandler - Exception caught in Netty
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: unknown_ca
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
Caused by: javax.net.ssl.SSLException: Received fatal alert: unknown_ca
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1094)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:966)

**Comment by To-om** [comment]
You have mixed truststore and keystore:
 - truststore is used to store certificate authorities.
 - keystore is used to store server certificate and its key.

You can configure them in application.conf file but if you choose to use command line parameters you must use:
```
bin/thehive
  -Dconfig.file=/opt/thehive/etc/application.conf
  -Djavax.net.ssl.keyStore=/path/to/keystore.jks
  -Djavax.net.ssl.keyStorePassword=keystorePassword
  -Djavax.net.ssl.trustStore=/path/to/truststore.jks
  -Djavax.net.ssl.trustStorePassword=truststorePassword
```

**Comment by JohnOmernik** [comment]
So "mixed" is a funny word. I knew that in the play configuration I used truststore per 
https://github.com/CERT-BDF/TheHive/wiki/Configuration

9. HTTPS

To enable HTTPS in the application, add the following lines to /etc/thehive/application.conf:

    https.port: 9443
    play.server.https.keystore {
      path: "/path/to/keystore.jks"
      type: "JKS"
      password: "password_of_keystore"
    }
As HTTPS is enabled HTTP can be disabled by adding http.port=disabled in configuration.

To import your certificate in the keystore, depending on your situation, you can follow Digital Ocean's tutorial.

More information: This is a setting of the Play framework that is documented on its website. Please refer to https://www.playframework.com/documentation/2.5.x/ConfiguringHttps.

Using only this, (no trust store information) I got the error above where the cert was autogenerated. Based on using the same process for generating a keystore and truststore for Apache Drill. (I.e. the trust/key stores are valid, and work find in Drill).  I made a guess that since I was providing a keystore with a certificate generated from my local Certificate Authority, The play framework decided against using it (it's invalid from it's perspective) and auto generated it's own.  Thus when I read the Authentication section of (section 3) of https://github.com/CERT-BDF/TheHive/wiki/Configuration and saw the parameters for providing a trust store, I had hoped it would solve the problem by using the keystore information in the application.conf, and then the trust store information as a command line option... 

I think the issue is related to the "self" signed cert in my keystore (it's trusted on my network).  I need to figure out when providing a keystore to the play framework, how I can also provide a trust store to the play framework.

**Comment by JohnOmernik** [comment]
Ah, this is a documentation issue... after troubleshooting and reading up, I turned on ssl.debug in play, and noticed, it was never getting my trust store information, as you can see in my previous post, the Configuration page, direct from the wiki has "play.server.https.keystore" That is NOT a valid play configuration item. The correct item is "play.server.https.keyStore" (note the upper case S)  Just changing that made it so everything worked, and all the stuff about the Truststore can be ignored....

**Comment by lanbus** [comment]
Hello,
Thanks a lot ! 
That was that for me too...
Regards,

**Comment by saadkadhi** [comment]
Thanks @JohnOmernik for your excellent pair of eyes. I've updated the documentation accordingly.
