### ISSUE TITLE
Pagination does not work with 100 results per page

### ISSUE THREAD

**Issue by derDuffy** [CERT-BDF/TheHive#152]
### Request Type
Bug

### Work Environment

| Question              | Answer
| Browser type & version    | Chrome(57.0.2987.110 (64-bit)), FF(52.0 (32-bit)) and IE(11.096)

### Problem Description
If selecting 100 results per page switching pages does not work. The system displays 2 pages correctly for 183 cases but switching to the second page does not work.
If result set size is decreased to 30 one will get 7 pages and switching pages works.

**Comment by nadouani** [comment]
Hi @derDuffy 

what are the pages concerned by this issue?

Thanks

**Comment by nadouani** [comment]
Hi @derDuffy 

We found the root cause of this issue: our use of Elasticsearch scroll queries doesn't take into account the pagination details. So, a quick workaround would to add the following config to your `application.conf` file

```
search.pagesize = 100
```

We will release a permanent fix to this issue on Mellifera (TheHive 2.11.0)

**Comment by To-om** [comment]
The problem is located in Elastic4play. An [issue](https://github.com/CERT-BDF/elastic4play/issues/12) have been created on its repo.

**Comment by nadouani** [comment]
This feature will be moved to 2.10.2 release
