### ISSUE TITLE
Can't get logs of a task via API

### ISSUE THREAD

**Issue by cheesecookie** [CERT-BDF/TheHive#259]
# Problem using API to get logs of tasks

### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Docker 
| OS version (client)       | Ubuntu
| TheHive version / git hash   | latest 2.12.0
| Package Type              | Docker
| Browser type & version    | If applicable

### Problem Description
I am trying to use the `GET /api/case/task/:id/log` but it keeps returning an empty list. 

However it works if I use 
```
POST /api/case/task/log/_search
{"query":{"_and":[{"_and":[{"_parent":{"_type":"case_task","_query":{"_id":"AV0_h2WNFclmdEbzNvAZ"}}},{"_not":{"status":"Deleted"}}]}]}}
```

**Comment by nadouani** [comment]
I confirm there is an unconsistency with this API and its documentation. After reading some code, it seems that this API uses a GET method, with a JSON body (which is not good).

But basically, for now, if you call it like following:

```
GET /api/case/task/:taskId/log
{
    "query": {
        "_not": {
            "status": "Deleted"
        }
    }
}'
```

So I'll keep this issue open, to be fixed, since this API, should be changed to either a GET without any request JSON body, or POST with a body.

**Comment by To-om** [comment]
`GET /api/case/task/:id/log` has been fixed.
I also add a new API `POST /api/case/task/:taskId/log/_search` which accepts a "query" in the request body to filter logs of the task.
