### ISSUE TITLE
Merge of cases overrides task log owners

### ISSUE THREAD

**Issue by derDuffy** [CERT-BDF/TheHive#303]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive version  | 2.12.0

### Problem Description
Describe the problem/bug as clearly as possible.

### Steps to Reproduce
1. Create case A (as user A)
1. Create a few tasks and log entries in Case A (as user A)
1. Create case B (as user B)
1. Merge case A into case B (as user B)
1. Observe that task logs originating from case A are assigned to user B now.

### Possible Solutions
Review merge functions

**Comment by nadouani** [comment]
Nice catch! Thanks @derDuffy 

It's not a big deal to fix it.

**Comment by To-om** [comment]
It is not easy to fix this issue because logs haven't owner, they only have creator (user who did the action). 
When a case is merged, logs are created in the new case and the creator is the user who initiate the merge action.

To fix this issue, I can add a new attribute "owner" to log entity but a schema update is required. I can also hack entity creation process to overwrite creator value.

This can't be done for TheHive 2.13

**Comment by To-om** [comment]
@nadouani in front-end, use attribute "owner" instead of "createdBy" (or "user") to show the owner of the log. This will solve this issue.
