### ISSUE TITLE
SLAs for Case Templates & Escalation/Due Dates for Cases

### ISSUE THREAD

**Issue by ecapuano** [CERT-BDF/TheHive#56]
### Feature Request

Would be great if a case template could have a pre-defined SLA such as "1 day, 3 days, etc" so that when a case is created from a template, it would have an automatic "Due Date" based on the pre-defined SLA. 

Due dates would help with prioritization of cases in high incident volume environments, and it would also help with escalation of cases to Sr Analysts in the event that SLAs are broken.

I've even seen implementations of two threshold dates, one for "due" and one for "escalation" so that it is escalated prior expiration, etc. 

Thoughts?

**Comment by saadkadhi** [comment]
Hi @ecapuano,

To some extent, this would require going the way of a ticketing system which is against our philosophy. We believe in people talking to each other instead of SLAs and have implemented a few features such as **Cold cases**, **case and task flagging** as well as the **my tasks** and **waiting tasks** notifications to get them to work together and get the job done.

We feel that, by implementing due dates, SLAs and such, TH will be yet another tool stripping away our social and communication abilities. 

I will close this feature request for the time being and if there's a huge push (with sound agreements) from our user base, then we'll reconsider.

Thank you for your understanding.

**Comment by obikao** [comment]
While I totally understand the philosophical aspect of this, it prevents this from being used at scale. SLAs aren't there to strip away communications, they exist for the purposes of staffing. ie. if we consistently aren't meeting our SLAs, then we have a staffing problem and need to hire more people. Being able to show irrefutable data to upper management on why we need more people is key when making business cases.
