### ISSUE TITLE
Version 2.10.0

### ISSUE THREAD

**Issue by eliebilly** [CERT-BDF/TheHive#85]
### Request Type
Question

Bonjour,
Quand sortira la version 2.10.0 ?

Cordialement

**Comment by nadouani** [comment]
Hello @eliebilly, sorry for saying that, but I have to make two comments about the issue your created here:

1. As you can see, the official language of this repo is English. So, could you please ask your questions in English, so that everybody could understand what your are asking for
1. Github issues are used to give feedback about bugs you encounter, new feature or improvements you would like to have access to, within TheHive. If you have questions related to something else, please use the Users Forum or the Support Forum (https://github.com/CERT-BDF/TheHive#community-discussions).

With that said, the 2.10.0 release introduce a lot of feature and is currently being tested before the public release (which should be available in the next few days, maybe by the end of the next week).

I hope I answered your question.

Thanks
